### ISSUE TITLE
Computer cannot find new fonts for the AllHands template

### ISSUE THREAD

**Issue by nategarton13** [CSAFE-ISU/Templates#1]
Has anyone been able to get the new poster template working? Latex produces the following error: 

"! Package fontspec Error: The font "Sanchez-Italic" cannot be found."

I've installed the new fonts, including "Sanchez-Italic". The log file makes it seem like it is still trying to install the new fonts.

**Comment by nategarton13** [comment]
Commenting
 %\newfontfamily\sanchez[UprightFont={*-Italic}]{Sanchez} 
fixes this.

**Comment by sctyner** [comment]
I got the same error today! I was able to install the Sanchez italic font onto my computer from Google Fonts: https://fonts.google.com/specimen/Sanchez?selection.family=Sanchez. 

Once you download the font file from Google, install the font on your computer, and you should be good to go. (That's what fixed it for me at least!)

**Comment by sctyner** [comment]
I guess the fonts are also in the helpfully named "fonts" folder in the baposter_template folder. 
 
![](https://media3.giphy.com/media/hVmCCt5ikEUQ8/giphy.gif)

**Comment by nategarton13** [comment]
Yeah, that's interesting. Even after installing the fonts from the fonts folder, I was still having an issue with sanchez-italic. I wondered if they were installed in the wrong location or something. In any case, good to know the installation will work for others!
